name: C/C++ CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: start
      run: mkdir build
    - name: move to build folder
      run: cd build
    - name: cmake
      run: cmake ..
    - name: make
      run: make
