name: C/C++ CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: start
      run: ls -R
    - name: build directory init
      run: mkdir build
      working-directory: "./1. Process"
    - name: cmake
      run: cmake ..
      working-directory: "./1. Process/build"
    - name: make
      run: make
      working-directory: "./1. Process/build"
